### ISSUE TITLE
plotly dropdown isn't displaying traces properly

### ISSUE THREAD

**Issue by amilovanovikj** [Notebook-Factory/gropt_book#1]
I have an issue with the plotly dropdown menu where on running the cell in the notebook it plots all traces, instead of the ones I selected for the active item in the dropdown menu. After reselecting the item from the menu it works fine, but the initial display is incorrect, showing all my plots at once. The notebook in question is located in the "python" folder, under the name "interactive_figures.ipynb"

**Comment by agahkarakuzu** [comment]
Hey @amilovanovikj you can set visible=False for all the traces when they are first instantiated, then upon first selection only the active ones are displayed. 

You can leave only one visible as default and update layouts accordingly to give ppl a better idea about what's being displayed.

**Comment by amilovanovikj** [comment]
That worked, thanks! I'm closing this issue
