### ISSUE TITLE
Dropdown menu update method not working properly

### ISSUE THREAD

**Issue by amilovanovikj** [Notebook-Factory/gropt_book#2]
When I use the update method on plotly dropdown menu, only restyle is applied, and not relayout. Hence, the horizontal and vertical lines (on last 2 plots in the dropdown menu) fail to draw. I don't know if this is meant to happen (which I highly doubt, since the documentation [here](https://plotly.com/python/dropdowns/#methods) explains that using this method will behave like restyle and relayout are used in combination, which is what I need) or I am doing something wrong, or maybe there is a bug in the plotly library. Note that if I use relayout instead of update, the lines are drawn, but the traces aren't updated (restyle is not applied), resulting in drawing the lines on the wrong plot. The notebook in question is at [python/interactive_figures.ipynb](https://github.com/Notebook-Factory/gropt_book/blob/main/python/interactive_figures.ipynb)

**Comment by zelenkastiot** [comment]
@agahkarakuzu Do you have an idea how this might be handled? I do agree with @amilovanovikj looks like a feature not working.

**Comment by agahkarakuzu** [comment]
I'll look into this and let you know 👍

**Comment by agahkarakuzu** [comment]
@amilovanovikj can you let me know which stepts to follow to import `gropt` properly? 

```
python setup.py build_ext --inplace
```

is not working, maybe there is an easier way?

**Comment by agahkarakuzu** [comment]
@amilovanovikj since I cannot execute this notebook not sure if this is the issue, instead of 

```python
 args = [{"visible": [True if x < Naxis else False for x in range(2*Naxis+5)],
                             "shapes":[],
                             'xaxis': {'title': "$t [ms]$"},
                             'showlegend':False}]),
```

can you try 
```python
 args = [{"visible": [True if x < Naxis else False for x in range(2*Naxis+5)]},
                             {"shapes":[],
                             'xaxis': {'title': "$t [ms]$"},
                             'showlegend':False}}]),
```

The difference here is that the layout attributes are passed as a second arg as dictionary. Intuitively, you should pass separate instructions for layout and trace attributes, let me know if this works out. You'll need to apply this to the every instance of `args`.

**Comment by amilovanovikj** [comment]
@agahkarakuzu  Thanks, this worked

> @amilovanovikj since I cannot execute this notebook not sure if this is the issue, instead of
> 
> ```python
>  args = [{"visible": [True if x < Naxis else False for x in range(2*Naxis+5)],
>                              "shapes":[],
>                              'xaxis': {'title': "$t [ms]$"},
>                              'showlegend':False}]),
> ```
> 
> can you try
> 
> ```python
>  args = [{"visible": [True if x < Naxis else False for x in range(2*Naxis+5)]},
>                              {"shapes":[],
>                              'xaxis': {'title': "$t [ms]$"},
>                              'showlegend':False}}]),
> ```
> 
> The difference here is that the layout attributes are passed as a second arg as dictionary. Intuitively, you should pass separate instructions for layout and trace attributes, let me know if this works out. You'll need to apply this to the every instance of `args`.

Also, as a note, this notebook can only be run on Windows machines because of the file in python/gropt.cp37-win_amd64.pyd is the one that builds the library and can only be executed on Windows.
